
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "cloud-run-1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-1.service_uri
}
output "cloud-run-2_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-2.service_uri
}
output "cloud-run-3_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-3.service_uri
}
output "cloud-run-4_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-4.service_uri
}
output "memorystore-1_host" {
  description = "The IP address of the instance."
  value       = module.memorystore-1.host
}
output "memorystore-1_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.memorystore-1.port
}
output "cloud-run-5_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-5.service_uri
}
output "cloud-run-6_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-6.service_uri
}
