# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "project_id" {
  description = "The GCP project ID to deploy all resources to."
  type        = string
}
variable "location" {
  description = "The GCP location/region to deploy all resources to."
  type        = string
}
variable "lb-backend-1_name" {
  description = "Name for the backend service."
  type        = string
}
variable "memorystore-1_name" {
  description = "The ID of the instance or a fully qualified identifier for the instance."
  type        = string
}
variable "firestore-1_database_id" {
  description = "Unique identifier of the Firestore Database."
  type        = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type        = string
}
