# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "project_id" {
  description = "The GCP project ID to deploy all resources to."
  type        = string
}
variable "location" {
  description = "The GCP location/region to deploy all resources to."
  type        = string
}
variable "lb-backend-1_name" {
  description = "Name for the backend service."
  type        = string
}
variable "memorystore-1_name" {
  description = "The ID of the instance or a fully qualified identifier for the instance."
  type        = string
}
variable "firestore-1_database_id" {
  description = "Unique identifier of the Firestore Database."
  type        = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type        = string
}
variable "agent_createworld_url" {
  description = "The service URL for the agent-createworld Cloud Run service."
  type        = string
  default     = ""
}
variable "agent_createcharacter_url" {
  description = "The service URL for the agent-createcharacter Cloud Run service."
  type        = string
  default     = ""
}
variable "agent_narrative_url" {
  description = "The service URL for the agent-narrative Cloud Run service."
  type        = string
  default     = ""
}
variable "agent_optiongen_url" {
  description = "The service URL for the agent-optiongeneration Cloud Run service."
  type        = string
  default     = ""
}

# ── Cloud Build / CI variables ─────────────────────────────────────────────────

variable "github_owner" {
  description = "GitHub organisation or username that owns the repository."
  type        = string
}

variable "github_repo" {
  description = "GitHub repository name (without the owner prefix)."
  type        = string
}

variable "artifact_registry_repo" {
  description = "Artifact Registry repository ID used to store agent Docker images."
  type        = string
  default     = "cloud-run-source-deploy"
}

variable "github_app_installation_id" {
  description = "Installation ID of the Cloud Build GitHub App on your GitHub account/org. Found in the GitHub App settings URL."
  type        = number
}

variable "github_oauth_token_secret_version" {
  description = "Full Secret Manager secret version resource name holding the GitHub OAuth token used by the Cloud Build connection. Format: projects/PROJECT/secrets/SECRET/versions/VERSION"
  type        = string
}
