
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "cloud-run-1_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-1_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "lb-backend-1_name" {
  description = "Name for the backend service."
  type = string
}
variable "lb-backend-1_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "cloud-run-2_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-2_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "cloud-run-3_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-3_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "cloud-run-4_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-4_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "memorystore-1_project_id" {
  description = "The ID of the project in which the resource belongs to."
  type = string
}
variable "memorystore-1_region" {
  description = "The GCP region to use."
  type = string
}
variable "memorystore-1_name" {
  description = "The ID of the instance or a fully qualified identifier for the instance."
  type = string
}
variable "cloud-run-5_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-5_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "cloud-run-6_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "cloud-run-6_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "firestore-1_project_id" {
  description = "The ID of the project in which the Firestore resources are created."
  type = string
}
variable "firestore-1_database_id" {
  description = "Unique identifier of the Firestore Database."
  type = string
}
variable "firestore-1_location" {
  description = "The location in which the Firesotre Database is created."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
